# Generated by Django 6.0.6 on 2026-06-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siec_przemyslowa_app_v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liniaprodukcyjna',
            name='Opis',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='maszynaprodukcyjna',
            name='Opis',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='urzadzeniemaszyny',
            name='Opis',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
