# Generated by Django 6.0.6 on 2026-06-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siec_przemyslowa_app_v1', '0002_liniaprodukcyjna_opis_maszynaprodukcyjna_opis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liniaprodukcyjna',
            name='Opis',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='maszynaprodukcyjna',
            name='Opis',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='urzadzeniemaszyny',
            name='Opis',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
