# Generated by Django 6.0.6 on 2026-06-30 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siec_przemyslowa_app_v1', '0003_alter_liniaprodukcyjna_opis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urzadzeniemaszyny',
            name='Maszyna_produkcyjna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urzadzenia_maszyny_produkcyjnej', to='siec_przemyslowa_app_v1.maszynaprodukcyjna'),
        ),
    ]
