# Generated by Django 6.0.6 on 2026-06-30 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siec_przemyslowa_app_v1', '0004_alter_urzadzeniemaszyny_maszyna_produkcyjna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maszynaprodukcyjna',
            name='Linia_produkcyjna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maszyny_linii_produkcyjnej', to='siec_przemyslowa_app_v1.liniaprodukcyjna'),
        ),
    ]
