# Generated by Django 6.0.6 on 2026-06-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siec_przemyslowa_app_v1', '0006_alter_urzadzeniemaszyny_rodzaj_urzadzenia'),
    ]

    operations = [
        migrations.AddField(
            model_name='urzadzeniemaszyny',
            name='Status_Polaczenia',
            field=models.IntegerField(blank=True, choices=[(0, 'Online'), (1, 'Offline')], default=1),
        ),
    ]
