# Generated by Django 6.0.6 on 2026-07-01 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siec_przemyslowa_app_v1', '0007_urzadzeniemaszyny_status_polaczenia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liniaprodukcyjna',
            options={'ordering': ['Nazwa_linii'], 'verbose_name': 'Lina Produkcyjna', 'verbose_name_plural': 'Linie produkcyjne'},
        ),
        migrations.AlterModelOptions(
            name='maszynaprodukcyjna',
            options={'ordering': ['Maszyna_nazwa'], 'verbose_name': 'Maszyna produkcyjna', 'verbose_name_plural': 'Maszyny produkcyjne'},
        ),
        migrations.AlterModelOptions(
            name='urzadzeniemaszyny',
            options={'ordering': ['Ip_Adres'], 'verbose_name': 'Urządzenie w maszynie', 'verbose_name_plural': 'Urządzenia w maszynie'},
        ),
    ]
