# Generated by Django 6.0.6 on 2026-07-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siec_przemyslowa_app_v1', '0008_alter_liniaprodukcyjna_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liniaprodukcyjna',
            name='Strefa_linia_produkcyjna',
            field=models.IntegerField(choices=[(1, 'WS1'), (2, 'WS2a'), (3, 'WS2b'), (4, 'WS3a'), (5, 'WS3b'), (6, 'WS4'), (7, 'WS5'), (8, 'WS6'), (9, 'WS7'), (10, 'WS8'), (11, 'WS9'), (12, 'WS10'), (20, 'STF1'), (21, 'STF2'), (22, 'STF3'), (23, 'STF4'), (24, 'STF5'), (25, 'STF6'), (26, 'STF7')]),
        ),
    ]
