# Generated by Django 6.0.6 on 2026-07-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siec_przemyslowa_app_v1', '0009_alter_liniaprodukcyjna_strefa_linia_produkcyjna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urzadzeniemaszyny',
            name='Rodzaj_Urzadzenia',
            field=models.IntegerField(choices=[(1, 'LOGO! 8'), (2, 'LOGO! 8.3'), (10, 'SIMATIC S7-200'), (11, 'SIMATIC S7-200 CN'), (20, 'SIMATIC S7-200 SMART'), (30, 'SIMATIC S7-300'), (40, 'SIMATIC S7-400'), (41, 'SIMATIC S7-400H'), (42, 'SIMATIC S7-400F'), (43, 'SIMATIC S7-400FH'), (50, 'SIMATIC S7-1200'), (51, 'SIMATIC S7-1200 G2'), (60, 'SIMATIC S7-1500'), (61, 'SIMATIC S7-1500T'), (62, 'SIMATIC S7-1500F'), (63, 'SIMATIC S7-1500TF'), (64, 'SIMATIC S7-1500H'), (65, 'SIMATIC S7-1500HF'), (66, 'SIMATIC S7-1500R'), (67, 'SIMATIC S7-1500RF'), (70, 'SIMATIC ET 200SP CPU'), (71, 'SIMATIC ET 200pro CPU'), (72, 'SIMATIC ET 200eco PN CPU'), (80, 'SIMATIC S7-1500 Software Controller'), (81, 'SIMATIC WinAC'), (90, 'SIMATIC S7-1500 Open Controller'), (201, 'KTP400 Basic'), (202, 'KTP700 Basic'), (203, 'KTP900 Basic'), (204, 'KTP1200 Basic'), (205, 'TP700 Comfort'), (206, 'TP900 Comfort'), (207, 'TP1200 Comfort'), (208, 'TP1500 Comfort'), (209, 'TP1900 Comfort'), (210, 'TP2200 Comfort'), (211, 'KP700 Comfort'), (212, 'KP900 Comfort'), (213, 'KP1200 Comfort'), (214, 'Unified Comfort TP700'), (215, 'Unified Comfort TP900'), (216, 'Unified Comfort TP1200'), (217, 'Unified Comfort TP1500'), (218, 'Unified Comfort TP1900'), (219, 'Unified Comfort TP2200'), (220, 'Unified Basic MTP700'), (221, 'Unified Basic MTP1000'), (222, 'Mobile Panel 2nd Generation'), (223, 'Mobile Panel 277'), (224, 'KP8'), (225, 'KP8F'), (226, 'KP32F'), (227, 'IPC127E'), (228, 'IPC227E'), (229, 'IPC427E'), (230, 'IPC477E Panel PC'), (231, 'IPC677E Panel PC'), (301, 'Keyence SR-700'), (302, 'Keyence SR-710'), (303, 'Keyence SR-750'), (304, 'Keyence SR-1000'), (305, 'Keyence SR-1000W'), (306, 'Keyence SR-2000'), (307, 'Keyence SR-2000W'), (308, 'Keyence HR-50'), (309, 'Keyence HR-51'), (310, 'Keyence HR-52'), (320, 'Cognex DataMan 150'), (321, 'Cognex DataMan 260'), (322, 'Cognex DataMan 262'), (323, 'Cognex DataMan 360'), (324, 'Cognex DataMan 370'), (325, 'Cognex DataMan 470'), (326, 'Cognex DataMan 475'), (327, 'Cognex DataMan 503'), (328, 'Cognex DataMan 8072'), (329, 'Cognex DataMan 8050'), (330, 'Cognex DataMan 8050X'), (331, 'Cognex DataMan 8700'), (1000, 'Urządzenie nieznane')]),
        ),
    ]
