# Generated by Django 6.0.6 on 2026-07-06 04:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siec_przemyslowa_app_v1', '0011_alter_liniaprodukcyjna_strefa_linia_produkcyjna'),
    ]

    operations = [
        migrations.CreateModel(
            name='PLCMaszyna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ip_Adres', models.CharField(max_length=17, unique=True, validators=[django.core.validators.MinLengthValidator(7)])),
                ('Profinet_name', models.CharField(max_length=17, unique=True, validators=[django.core.validators.MinLengthValidator(7)])),
                ('Rack', models.IntegerField(default=0)),
                ('Slot', models.IntegerField(default=1)),
                ('Typ_sterownika', models.IntegerField(blank=True, choices=[(1, 'LOGO! 8'), (2, 'LOGO! 8.3'), (10, 'SIMATIC S7-200'), (11, 'SIMATIC S7-200 CN'), (20, 'SIMATIC S7-200 SMART'), (30, 'SIMATIC S7-300'), (40, 'SIMATIC S7-400'), (41, 'SIMATIC S7-400H'), (42, 'SIMATIC S7-400F'), (43, 'SIMATIC S7-400FH'), (50, 'SIMATIC S7-1200'), (51, 'SIMATIC S7-1200 G2'), (60, 'SIMATIC S7-1500'), (61, 'SIMATIC S7-1500T'), (62, 'SIMATIC S7-1500F'), (63, 'SIMATIC S7-1500TF'), (64, 'SIMATIC S7-1500H'), (65, 'SIMATIC S7-1500HF'), (66, 'SIMATIC S7-1500R'), (67, 'SIMATIC S7-1500RF'), (70, 'SIMATIC ET 200SP CPU'), (71, 'SIMATIC ET 200pro CPU'), (72, 'SIMATIC ET 200eco PN CPU'), (80, 'SIMATIC S7-1500 Software Controller'), (81, 'SIMATIC WinAC'), (90, 'SIMATIC S7-1500 Open Controller')], default=1)),
                ('Maszyna_produkcyjna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sterowniki_maszyny_produkcyjnej', to='siec_przemyslowa_app_v1.maszynaprodukcyjna')),
            ],
        ),
    ]
