# Generated by Django 6.0.6 on 2026-07-06 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siec_przemyslowa_app_v1', '0012_plcmaszyna'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plcmaszyna',
            options={'ordering': ['Ip_Adres'], 'verbose_name': 'Sterownik PLC', 'verbose_name_plural': 'Sterowniki PLC'},
        ),
        migrations.AlterModelTable(
            name='liniaprodukcyjna',
            table='db_linie_produkcyjne',
        ),
        migrations.AlterModelTable(
            name='maszynaprodukcyjna',
            table='db_maszyny_produkcyjne',
        ),
        migrations.AlterModelTable(
            name='plcmaszyna',
            table='db_sterowniki_plc',
        ),
        migrations.AlterModelTable(
            name='urzadzeniemaszyny',
            table='db_urzadzenia_maszyn',
        ),
    ]
