# Generated by Django 6.0.6 on 2026-07-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siec_przemyslowa_app_v1', '0013_alter_plcmaszyna_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plcmaszyna',
            name='Status_Polaczenia',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='plcmaszyna',
            name='Typ_sterownika',
            field=models.IntegerField(blank=True, choices=[(1, 'LOGO! 8'), (2, 'LOGO! 8.3'), (10, 'SIMATIC S7-200'), (11, 'SIMATIC S7-200 CN'), (20, 'SIMATIC S7-200 SMART'), (30, 'SIMATIC S7-300'), (40, 'SIMATIC S7-400'), (41, 'SIMATIC S7-400H'), (42, 'SIMATIC S7-400F'), (43, 'SIMATIC S7-400FH'), (50, 'SIMATIC S7-1200'), (51, 'SIMATIC S7-1200 G2'), (60, 'SIMATIC S7-1500'), (61, 'SIMATIC S7-1500T'), (62, 'SIMATIC S7-1500F'), (63, 'SIMATIC S7-1500TF'), (64, 'SIMATIC S7-1500H'), (65, 'SIMATIC S7-1500HF'), (66, 'SIMATIC S7-1500R'), (67, 'SIMATIC S7-1500RF'), (70, 'SIMATIC ET 200SP CPU'), (71, 'SIMATIC ET 200pro CPU'), (72, 'SIMATIC ET 200eco PN CPU'), (80, 'SIMATIC S7-1500 Software Controller'), (81, 'SIMATIC WinAC'), (90, 'SIMATIC S7-1500 Open Controller'), (1000, 'UNKNOWN CONTROLLER')], default=1000),
        ),
    ]
