# Generated by Django 6.0.6 on 2026-07-03 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drukarki_etykiet_app_v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'verbose_name': 'Etykieta', 'verbose_name_plural': 'Etykiety'},
        ),
        migrations.AlterModelOptions(
            name='printer',
            options={'verbose_name': 'Drukarka Etykiet', 'verbose_name_plural': 'Drukarki Etykiet'},
        ),
        migrations.AlterModelTable(
            name='label',
            table='db_etykiety',
        ),
        migrations.AlterModelTable(
            name='printer',
            table='db_drukarki',
        ),
    ]
