# Generated by Django 6.0.6 on 2026-07-03 21:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drukarki_etykiet_app_v1', '0002_alter_label_options_alter_printer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='model',
            field=models.CharField(choices=[('ZD220D', 'Zebra ZD220d'), ('ZD220T', 'Zebra ZD220t'), ('ZD230D', 'Zebra ZD230d'), ('ZD230T', 'Zebra ZD230t'), ('ZD411', 'Zebra ZD411'), ('ZD421', 'Zebra ZD421'), ('ZD611', 'Zebra ZD611'), ('ZD621', 'Zebra ZD621'), ('GK420D', 'Zebra GK420d'), ('GK420T', 'Zebra GK420t'), ('GX420D', 'Zebra GX420d'), ('GX420T', 'Zebra GX420t'), ('GX430T', 'Zebra GX430t'), ('ZT220', 'Zebra ZT220'), ('ZT230', 'Zebra ZT230'), ('ZT231', 'Zebra ZT231'), ('ZT410', 'Zebra ZT410'), ('ZT411', 'Zebra ZT411'), ('ZT420', 'Zebra ZT420'), ('ZT421', 'Zebra ZT421'), ('ZT510', 'Zebra ZT510'), ('ZT610', 'Zebra ZT610'), ('ZT620', 'Zebra ZT620'), ('ZM400', 'Zebra ZM400'), ('S4M', 'Zebra S4M'), ('105SLPLUS', 'Zebra 105SL Plus'), ('OTHER', 'Inny model')], default='OTHER'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='ip',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.MinLengthValidator(7)]),
        ),
    ]
