# Generated by Django 6.0.6 on 2026-07-04 00:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drukarki_etykiet_app_v1', '0003_printer_model_alter_printer_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
