# Generated by Django 6.0.6 on 2026-07-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drukarki_etykiet_app_v1', '0005_label_pattern_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='pattern_label',
            field=models.CharField(choices=[('QR', '^XA\n    ^FT25,200^BQN,2,6\n    ^FH\\^FDLA,**Wpisz_Tutaj**^FS\n    ^PQ1,0,1,Y^XZ\n'), ('DATAMATRIX', '^XA\n    ^FT25,190^BXN,8,200,0,0,1,~\n    ^FH\\^FD**Wpisz_tutaj**^FS\n\\^PQ1,0,1,Y^XZ\n'), ('UNKNOWN', 'UNKNOWN')], default='DATAMATRIX'),
        ),
    ]
