# Generated by Django 6.0.6 on 2026-07-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drukarki_etykiet_app_v1', '0006_alter_label_pattern_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='type_code',
            field=models.CharField(choices=[('DATAMATRIX', 'datamatrix'), ('QR', 'qr'), ('PDF_417', 'pdf_417'), ('MERCEDES', 'Mercedes'), ('DWG_FIAT', 'dwg_fiat'), ('INC_DATA_MATRIX', 'Inc Data Matrix'), ('CNH1', 'cnh1'), ('CNH2', 'cnh2'), ('QR_TEXT', 'qr_text'), ('QR1', 'qr1'), ('QR2', 'qr2'), ('DATAMATRIX_PLUS_TITLE', 'datamatrix_plus_title'), ('UNKNOWN', 'unknown')], default='UNKNOWN'),
        ),
    ]
