# Generated by Django 6.0.6 on 2026-07-04 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drukarki_etykiet_app_v1', '0007_label_type_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['id'], 'verbose_name': 'Etykieta', 'verbose_name_plural': 'Etykiety'},
        ),
    ]
