# Generated by Django 6.0.6 on 2026-07-04 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drukarki_etykiet_app_v1', '0008_alter_label_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='pattern_label',
        ),
    ]
